name: pr-loop
run-name: pr loop for solution using dotnet build on cdsproj

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: src/pcfs/LinearInputControl/package-lock.json

      - name: cache-nuget
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # - name: npm install for pcf
      #   shell: pwsh
      #   run: |
      #     $currentLocation = Get-Location
      #     $fullPath = "$currentLocation\src\pcfs\LinearInputControl"
      #     echo $fullPath
      #     npm install --prefix $fullPath


      - name: Restore dependencies        
        run: dotnet restore --source /src

      - name: Build
        run: dotnet build --source /src --no-restore --configuration release

      - name: Test
        run: dotnet test --source /src --no-build --verbosity normal
